### ISSUE TITLE
[Feature Request] Search/Filter feature

### ISSUE THREAD

**Issue by Crunchbits** [boiwantlearncode/multiple-bookmarker#1]
First, thank you for the great extension! It's so useful, even for single tab bookmarking it's really fast.

I think a feature that would help improve the extension would be the ability to search for bookmarks. That is to say that at the beginning of the popup you could start typing automatically and it would show matching folders as you type or delete the query. If implemented I would suggest having keyboard options so that the first option at the top is always focused so you can quickly press enter to add it to the folder.

**Comment by boiwantlearncode** [comment]
Hi, thanks for the feedback! I really like your ideas. I'll work on the search feature!

**Comment by boiwantlearncode** [comment]
Hi @Crunchbits, I have implemented the search feature, hope you can give a review on it. Unfortunately, to make it work, the text input value has to be bound to the local storage, which causes a very slight delay in the update of the value. In other words, you can't type too fast. 

Next up I will add the "autofocus on the first option and press enter to select" feature.

**Comment by boiwantlearncode** [comment]
I've fixed the delay. The issue was that using `innerHTML` resets the existing input value. It also removes existing event listeners attached to that element and its descendants. 

To counter this, I had the input bound to the local storage so that the input value is saved for every single input event. This causes some delay. On v1.2.1, I used `insertAdjacentHTML` instead of `innerHTML` which does not have the aforementioned two problems, making it way simpler to implement on top of eliminating the delay problem.

**Comment by Crunchbits** [comment]
I was going to reply earlier today because I had tested out v1.2 and I was getting inconsistent results with the text field actually focusing at the start + the folder list actually filtering/removing folders when typing (Even slowly). However, after testing out v1.2.1, all of those issues seem to be fixed!

The only issue that I am having in regards to search filtering is a strange bug. When I bookmark without typing/filtering by just clicking the folder, it works as expected. However, when I type anything in the text field (even including if I backspace to have it blank again) and then click the folder to bookmark, it bookmarks correctly but gets multiple duplicates. I've had anywhere from 2-7 duplicates of the same bookmark when I do it like that and it happens every time I type something.

Using Firefox stable release v122.0.

**Comment by boiwantlearncode** [comment]
Thanks I'm working on the duplicate issue. Turns out it's because every input on the search bar creates an event listener to each bookmark folder. Somehow the previous event listeners attached to each bookmark folder doesn't get destroyed even though the nodes of the bookmark folders are destroyed on each render.

**Comment by boiwantlearncode** [comment]
My bad I've been really busy, I finally fixed it :). v1.2.2 has been released with the fix.

**Comment by boiwantlearncode** [comment]
MAJOR UPDATE
I've uploaded v1.3!

I really like your ideas @Crunchbits and I added a bit more. You can navigate through your folders using your UP and DOWN arrow keys, and pressing enter will bookmark your selected tabs into the highlighted folder.

One issue though is sometimes the text cursor isn't automatically focused on the search bar. Thanks again for your feedback!

**Comment by Crunchbits** [comment]
Oh this is soo good! Seriously so useful! I haven't experienced any issues with the focus on the search bar but perhaps I have to use it more. One last thing in regards to keyboard navigation I'd suggest would be a configurable keyboard shortcut to open/close the popup. Regardless this is now my actual favorite extension on Firefox and I have 50+ extensions.

**Comment by boiwantlearncode** [comment]
Haha that's really great to hear. I'll close this issue and open a new one with regards to your next feature request.
